name: detect secrets
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: install python3.9
        with:
          python-version: 3.9
      - run: pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
        name: install detect-secrets
      - run: detect secrets
        name: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
